### ISSUE TITLE
list of hamnosys symbols and their function

### ISSUE THREAD

**Issue by LinguList** [lingpy/pysign#2]
specifically important: if a symbol indicates segmentation, but also if it is for handshapes, movements, etc., 

For grouping symbols (brackets), it would be good to have a tag for "open" and "close".

This can be a tsv file, with a header:

symbol | unicode | name | domain | type 
--- | --- | --- | --- | --- 
X | E001 | flathand | shape | base
Y | EOEA | dominant | hand | flag
Z |  007B | altbegin | group | start
A | 007D | altend | group | stop

etc.

I assume you will have better ideas, @justopower, to make this more consistent. It is just what I saw there now. This essential info will help us to make the parser, but also be useful for other aspects (imagine a web application that would allow you to type hamnosys by writing "flathand dominant altbegin altend", even with autocomplete (!).

**Comment by LinguList** [comment]
The file where you can add this information is: [src/pysign/data/](https://github.com/lingpy/pysign/blob/master/src/pysign/data/hamnosys.tsv)

**Comment by justopower** [comment]
> specifically important: if a symbol indicates segmentation, but also if it is for handshapes, movements, etc.,
> 
> For grouping symbols (brackets), it would be good to have a tag for "open" and "close".
> 
> This can be a tsv file, with a header:
> 
> symbol	unicode	name	domain	type
> X	E001	flathand	shape	base
> Y	EOEA	dominant	hand	flag
> Z	007B	altbegin	group	start
> A	007D	altend	group	stop
> etc.
> 
> I assume you will have better ideas, @justopower, to make this more consistent. It is just what I saw there now. This essential info will help us to make the parser, but also be useful for other aspects (imagine a web application that would allow you to type hamnosys by writing "flathand dominant altbegin altend", even with autocomplete (!).

Ok, this will take some time, but I have some ideas for starting out. 'base' will mean specific only to that segment type. Some symbols cross-cut segment types, so maybe they should not be called 'base'. Any ideas?

We can also use the hamnosys names for now, and then later possibly devise some more succinct names, because some hamnosys names are long and hard to understand.

**Comment by LinguList** [comment]
A, "base" would mean, this is a non-diacritic symbol, I'd say, so symbols that usually occur at the first part of a sequence, etc., so the opposite I would call it "diacritic".

**Comment by justopower** [comment]
Ok, have a look at `src/pysign/data/hamsymbols.tsv` to see the updated tsv file. You can say what looks helpful and what not, and we can change it as needed. I added a subdomain there, because I think that may be useful in the future, even if for now it is not clear how to assign the subdomains.

**Comment by LinguList** [comment]
nice, so we start from there. We'll have the simple translation function, which is already running, so we only need to replace the file.
